# For local development only.

services:
  phalcon-volt-8.1:
    container_name: phalcon-volt-8.1
    hostname: phalcon-volt-8.1
    build: .docker/8.1
    tty: true
    working_dir: /srv
    volumes:
      - .:/srv
